#spring:
#  application:
#    name: Badge and Membership Management
#  datasource:
#    url: jdbc:sqlserver://localhost:1433;databaseName=CS544-202303-05;encrypt=true;trustServerCertificate=true;
#    username: sa
#    password: secret123
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.SQLServerDialect
#        format_sql: true
#    generate-ddl: true
#    show-sql: false
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always